- name: Install Nginx
  dnf:
    name: nginx
    state: present

- name: Create apps directory
  file:
    path: "{{ apps_directory }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
