version: '3.8'

volumes:
  readeck-data:

services:
  readeck:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    restart: unless-stopped
    ports:
      - "${READECK_SERVER_PORT}:${READECK_SERVER_PORT}"
    volumes:
      - readeck-data:/readeck
    environment:
      - READECK_LOG_LEVEL=${READECK_LOG_LEVEL}
      - READECK_SERVER_HOST=${READECK_SERVER_HOST}
      - READECK_SERVER_PORT=${READECK_SERVER_PORT}
    healthcheck:
      test: ["/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3