- name: Install Nginx
  dnf:
    name: nginx
    state: present

- name: Deploy Nginx config for Readeck
  template:
    src: readeck.conf.j2
    dest: /etc/nginx/conf.d/readeck.conf
  notify: restart nginx

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
