---
# Example configuration for a second application
# Copy this file to create new app configurations

app_name: nextapp
domain_name: nextapp.example.com
user_email: your-email@example.com
container_port: 8001  # Must be unique!
app_directory: "/home/ec2-user/apps/nextapp"

# Docker configuration
docker_image: "nginx:alpine"  # Replace with your app's image
container_name: nextapp
restart_policy: unless-stopped

# Environment variables (optional)
environment_vars:
  - "APP_ENV=production"
  - "LOG_LEVEL=info"

# Volume mounts (optional)
volumes:
  - "nextapp-data:/app/data"
  - "nextapp-config:/app/config"

# Health check configuration (optional)
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
  interval: 30s
  timeout: 5s
  retries: 3

# Nginx configuration
nginx_config:
  client_max_body_size: 50M
  proxy_timeout: 30s
  additional_headers:
    - 'add_header X-App-Name "NextApp" always'
  custom_locations:
    - path: "/api"
      directives:
        - "proxy_pass http://localhost:8001/api"
        - "proxy_buffering off"

# SSL configuration
ssl_enabled: true
auto_start: true

# Dependencies (optional) - start after these containers
# depends_on:
#   - "database"