---
# Readeck Application Configuration
app_name: readeck
domain_name: readeck.migacloud.dev
user_email: marlujan.hj+dev1@gmail.com
container_port: 8000
app_directory: "/home/ec2-user/apps/readeck"

# Docker configuration
docker_image: "codeberg.org/readeck/readeck:latest"
container_name: readeck
restart_policy: unless-stopped

# Environment variables
environment_vars:
  - "READECK_LOG_LEVEL=debug"
  - "READECK_SERVER_HOST=0.0.0.0"
  - "READECK_SERVER_PORT=8000"

# Volume mounts
volumes:
  - "readeck-data:/readeck"

# Health check configuration
healthcheck:
  test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
  interval: 30s
  timeout: 2s
  retries: 3

# Nginx configuration
nginx_config:
  client_max_body_size: 100M
  proxy_timeout: 60s
  additional_headers:
    - 'add_header X-App-Name "Readeck" always'

# SSL configuration
ssl_enabled: true
auto_start: true