---
- name: Update Docker Compose Application
  hosts: docker_apps
  become: yes
  vars:
    app_config_path: "../{{ app_name }}/app.yml"
    app_compose_path: "../{{ app_name }}/docker-compose.yml"
    app_directory: "/home/ec2-user/apps/{{ app_name }}"

  pre_tasks:
    - name: Validate app_name parameter
      assert:
        that:
          - app_name is defined
          - app_name != ""
        fail_msg: "app_name must be provided. Use: -e app_name=<app_name>"

    - name: Load app configuration
      include_vars:
        file: "{{ app_config_path }}"
        name: app_config
      delegate_to: localhost

    - name: Display update info
      debug:
        msg:
          - "Updating application: {{ app_config.app_name }}"
          - "Domain: {{ app_config.domain_name }}"
          - "Services: {{ app_config.services.keys() | list | join(', ') }}"

  tasks:
    - name: Validate Docker Compose file exists
      stat:
        path: "{{ app_directory }}/docker-compose.yml"
      register: compose_file

    - name: Fail if Docker Compose file missing
      fail:
        msg: "Docker Compose file not found: {{ app_directory }}/docker-compose.yml"
      when: not compose_file.stat.exists

    - name: Update application with latest images
      community.docker.docker_compose_v2:
        project_src: "{{ app_directory }}"
        state: present
        pull: always
        recreate: always
      become_user: ec2-user
      register: compose_update

    - name: Wait for services to be ready
      pause:
        seconds: 10

  post_tasks:
    - name: Verify services health after update
      include_tasks: ../tasks/health_check.yml
      vars:
        service_name: "{{ item.key }}"
        service_config: "{{ item.value }}"
        app: "{{ app_config }}"
      loop: "{{ app_config.services | dict2items }}"
      when: item.value.proxy_port is defined

    - name: Display update status
      debug:
        msg: 
          - "✅ {{ app_config.app_name }} update completed!"
          - "🔄 Update result: {{ 'Containers updated' if compose_update.changed else 'No changes needed' }}"