---
- name: Update Docker Compose Application
  hosts: docker_apps
  become: yes
  vars:
    app_config_path: "../{{ app_name }}/app.yml"
    app_compose_path: "../{{ app_name }}/docker-compose.yml"
    app_directory: "/home/ec2-user/apps/{{ app_name }}"

  pre_tasks:
    - name: Validate app_name parameter
      assert:
        that:
          - app_name is defined
          - app_name != ""
        fail_msg: "app_name must be provided. Use: -e app_name=<app_name>"

    - name: Load app configuration
      include_vars:
        file: "{{ app_config_path }}"
        name: app_config
      delegate_to: localhost

    - name: Display update info
      debug:
        msg:
          - "Updating application: {{ app_config.app_name }}"
          - "Domain: {{ app_config.domain_name }}"
          - "Services: {{ app_config.services.keys() | list | join(', ') }}"

  tasks:
    - name: Pull latest Docker images
      community.docker.docker_compose:
        project_src: "{{ app_directory }}"
        pull: yes
        state: present
      become_user: ec2-user
      register: compose_pull

    - name: Recreate containers with latest images
      community.docker.docker_compose:
        project_src: "{{ app_directory }}"
        state: present
        recreate: always
      become_user: ec2-user
      register: compose_recreate

    - name: Wait for services to be ready
      pause:
        seconds: 10

  post_tasks:
    - name: Verify services health after update
      include_tasks: ../tasks/health_check.yml
      vars:
        service_name: "{{ item.key }}"
        service_config: "{{ item.value }}"
        app: "{{ app_config }}"
      loop: "{{ app_config.services | dict2items }}"
      when: item.value.proxy_port is defined

    - name: Display update status
      debug:
        msg: 
          - "✅ {{ app_config.app_name }} update completed!"
          - "🔄 Pull result: {{ 'Images updated' if compose_pull.changed else 'Already latest' }}"
          - "🐳 Recreate result: {{ 'Containers recreated' if compose_recreate.changed else 'No changes needed' }}"